version: "3"

services:
  mongodb:
      image: mongo:latest
      restart: always
      container_name: mongodb
      ports:
        - "27018:27017"
      volumes:
         - mongodb_data:/data/db
         - ./db:/data/backup/

  app:
      build:
        ./profilemanagement
      ports:
        - "3001:3000"
      volumes:
        - ./profilemanagement:/usr/src/app:rw
      links:
        - server
      command: npm start
      environment:
        env_file: .env
        NODE_ENV: development

  server:
      depends_on:
        - mongodb
      build:
        ./pmserver
      ports:
        - "3005:3005"
      volumes:
        - ./pmserver:/usr/src/server:rw
      links:
        - mongodb
      command: npm start

volumes:
  mongodb_data: {}