FROM mongo:latest

CMD mongo mongodb:27017

#COPY ./backup.json /backup.json
#
#COPY importdb.sh /
#
#RUN chmod +x /importdb.sh

#CMD mongoimport --host mongodb:27017 --db accountprofile --collection users --type json --file /backup.json --jsonArray

#CMD mongo --quiet --eval  "printjson(db.adminCommand('listDatabases'))"

#ENTRYPOINT ["sh", "/importdb.sh"]

#CMD mongoimport --host mongodb:27017 --db accountprofile --collection users --type json --file /temp/db/backup.json
#--jsonArray